name: AutoUpdate
on:
  schedule:
    - cron: '0 0 * * *' # 每天早上 8 點執行一次
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install -r requirements.txt
      - name: Scrape
        run: python scraper.py
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Data" || exit 0
          git push
